name: hello-snapcraftio
version: 2.0
summary: Snapcraft.io hello snap
description: This snap is the hello world for new snap users.
 1.x versions are in the stable channel and prints "Hello world!".
 2.x versions are in the beta channel and prints "Hello snap guru!".
 More info at https://snapcraft.io website.

apps:
  hello-snapcraftio:
    command: hello

parts:
  hello-command:
    plugin: copy
    files:
      hello: .
